### PR TITLE
Add support for TEAC UD-501/UD-503/NT-503

### PR DESCRIPTION
**Pull request by nobnob77**
This patch is reported as the issue#24: "[Solved] TEAC-503 native dsd".

### CODE REVIEW

**Comment by kimmot** [comment]
I have tested this patch by applying to to Daphile. One Daphile user who has TEAC UD-503 (0644:8043) tried it and got native DSD working but there was some background noise. Then I changed the DSD sample format used in patch from SNDRV_PCM_FMTBIT_DSD_U32_LE to SNDRV_PCM_FMTBIT_DSD_U32_BE and noise was gone.

**Comment by nobnob77** [comment]
Thank you for trying this patch.
First, I had a misunderstanding of the endian. "SNDRV_PCM_FMTBIT_DSD_U32_BE" is right. I already commit it.
And second, the burst noises on transions is resolved by the following patch in my environment. Try it please.

"native-dsd-noise-linux-4.0.8.patch" linked from this page.
https://sites.google.com/site/digififan/info/native-dsdzaishengshinopoppunoizuniduiyingshitakernelwogongkaishimashita

**Comment by kimmot** [comment]
Based on the first feedback from a Daphile user the patch with SNDRV_PCM_FMTBIT_DSD_U32_BE and "native-dsd-noise-linux-4.0.8.patch" together seems to work fine with TEAC UD-503. No more noise with native DSD, not even at track-to-track transitions. THANKS nobnob77!!!

**Comment by nobnob77** [comment]
I hope to merge this patch into the kernel src.
I will take the necesarry steps. 
"ALSA Development list" project is probably the right one.
So, I will close this pull request soon.

**Pull request closed without merging**
